disabled_rules:
- trailing_whitespace
- identifier_name
- type_name

line_length:
- 200 # warning
- 300 # error

file_length:
  warning: 600
  error: 1893

type_body_length: 
- 300 # warning
- 600 # error
